Vagrant.configure("2") do |config|

  config.vm.define "demovm" do |demovm|
    demovm.vm.box = "rupak_bhandari/rupakcentos7"
	  demovm.vm.network "private_network", ip: "192.168.10.11"
	  demovm.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
    end
  end
end
